---

- hosts: all
  become: true
  pre_tasks:

  - name: install apache and php
    tags: apache 
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: copy htmal_file file to all servere
    tags: apache
    copy:
      src: htmal_file
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: ensure httpd is running
    service:
      name: httpd 
      state: started

  - name: permit traffic in default zone for https service
    ansible.posix.firewalld:
      service: https
      permanent: yes
      state: enabled

  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted

