---

- hosts: all
  become: true
  tasks:

  - name: "Install appache" 
    yum:
      name:
        - httpd 
        - httpd-tools
      state: latest
      update_cache: yes
    when: ansible_distribution ==  "CentOS" 
