---

- hosts: all
  become: true
  tasks:

  - name: "Install appache" 
    package:
      name:
        - "{{ appache_package }}"
        - "{{ tool_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution ==  "CentOS" 
